name: resume-matcher

services:
  resume_matcher_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 7501:80
    secrets:
      - groq_key
      - llamacloud_key
    networks:
      - nginxproxymanager_default
  resume_matcher_mcp_server:
    build: 
      context: .
      dockerfile: Dockerfile.mcp_server
    ports:
      - 7502:8000
    secrets:
      - groq_key
      - linkup_key 
    networks:
      - nginxproxymanager_default
  resume_matcher_register:
    build: 
      context: .
      dockerfile: Dockerfile.register
    ports:
      - 7503:80
    secrets:
      - supa_key
      - supa_url
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true

secrets:
  groq_key:
    environment: groq_api_key
  linkup_key:
    environment: linkup_api_key
  llamacloud_key:
    environment: llamacloud_api_key
  supa_key:
    environment: supabase_key
  supa_url:
    environment: supabase_url